### ISSUE TITLE
Delete mybot.dart file

### ISSUE THREAD

**Issue by rohitagr0310** [Techie-AI/Frontend#31]
Remove the `mybot.dart` file from the repository as it is no longer needed.
**Tasks:**

- [x] Identify the `mybot.dart` file in the repository.
- [x] Delete the `mybot.dart` file.
- [x] Ensure that the deletion does not affect other parts of the project.
