### ISSUE TITLE
Add New Questions for User Responses

### ISSUE THREAD

**Issue by jayesh2474** [Techie-AI/Frontend#39]
#### Description

We need to update the list of questions that the chatbot asks users to gather their hardware requirements for PC builds. This includes fixing typos and ensuring all necessary components are covered.

#### Tasks

1. **Update Questions List:**
   - Correct the existing questions by fixing typos and adding missing commas.
   - Add the following questions:
     ```dart
     final List<String> _questions = [
       "Question 1: Which CPU you need?\n1. AMD\n2. Intel\n3. Apple\n4. ARM\n5. Hygon",
       "Question 2: How much CPU Power do you need?\n1. Low\n2. Mid\n3. High",
       "Question 3: Which company motherboard do you need?\n1. Asus\n2. Asrock\n3. Colorful\n4. MSI\n5. Biostar\n6. ECS\n7. Maxsun\n8. Fujitsu\n9. SOYO\n10. EVGA",
       "Question 4: How much motherboard Power do you need?\n1. Low\n2. Mid\n3. High",
       "Question 5: Which company RAM you need?\n1. Kingston\n2. Corsair\n3. G.Skill\n4. Crucial\n5. Samsung\n6. Patriot",
       "Question 6: How much RAM you need?\n1. 8GB\n2. 16GB\n3. 32GB",
       "Question 7: How much SSD Size you need?\n1. 256GB\n2. 512GB\n3. 1TB+"
     ];
     ```

2. **Update Maps:**
   - Update the existing maps to handle responses for all questions.
   - Example updates:
     ```dart
     final Map<String, Map<String, String>> cpus = {
       '1': {'category': 'AMD'},
       '2': {'category': 'Intel'},
       '3': {'category': 'Apple'},
       '4': {'category': 'ARM'},
       '5': {'category': 'Hygon'},
     };

     final Map<String, Map<String, String>> cpuPowers = {
       '1': {'power': 'Low'},
       '2': {'power': 'Mid'},
       '3': {'power': 'High'},
     };

     final Map<String, Map<String, String>> motherboards = {
       '1': {'company': 'Asus'},
       '2': {'company': 'Asrock'},
       '3': {'company': 'Colorful'},
       '4': {'company': 'MSI'},
       '5': {'company': 'Biostar'},
       '6': {'company': 'ECS'},
       '7': {'company': 'Maxsun'},
       '8': {'company': 'Fujitsu'},
       '9': {'company': 'SOYO'},
       '10': {'company': 'EVGA'},
     };

     final Map<String, Map<String, String>> motherboardPowers = {
       '1': {'power': 'Low'},
       '2': {'power': 'Mid'},
       '3': {'power': 'High'},
     };

     final Map<String, Map<String, String>> rams = {
       '1': {'company': 'Kingston'},
       '2': {'company': 'Corsair'},
       '3': {'company': 'G.Skill'},
       '4': {'company': 'Crucial'},
       '5': {'company': 'Samsung'},
       '6': {'company': 'Patriot'},
     };

     final Map<String, Map<String, String>> ramSizes = {
       '1': {'size': '8GB'},
       '2': {'size': '16GB'},
       '3': {'size': '32GB'},
     };

     final Map<String, Map<String, String>> ssdSizes = {
       '1': {'size': '256GB'},
       '2': {'size': '512GB'},
       '3': {'size': '1TB+'},
     };
     ```

3. **Update the `ChatScreen` Class:**
   - Ensure the updated questions list and maps are integrated into the `ChatScreen` class.
   - Ensure that user responses are processed correctly.

#### Acceptance Criteria
- [x] Questions list is updated and free of typos.
- [x] Maps are updated to handle responses for all questions.
- [x] The `ChatScreen` class is updated and functions correctly with the new questions.
- [x] The chatbot can collect user responses and generate prompts based on the updated questions.

---
