### ISSUE TITLE
Add Image to Bot Avatar in Chat Interface

### ISSUE THREAD

**Issue by jayesh2474** [Techie-AI/Frontend#40]
**Description:**
Enhance the chat interface by displaying an image for the bot's avatar. This will improve the visual appeal and user experience of the chat application.

**Steps to Implement:**
1. **Add Image to Assets:**
   - Place the bot avatar image (e.g., `bot_avatar.png`) in the `assets` directory of the project.

2. **Update `pubspec.yaml`:**
   - Include the asset in the `pubspec.yaml` file to ensure it's bundled with the app.
   ```yaml
   flutter:
     assets:
       - lib/bot_avatar.png
   ```

3. **Modify `ChatScreen` Widget:**
   - Update the code where the `CircleAvatar` for the bot is created to use the new image.
   ```dart
   if (message.sender == 'Bot')
     CircleAvatar(
       backgroundImage: AssetImage('lib/bot_avatar.png'),
     ),
   ```

**Expected Outcome:**
When the bot sends a message, the bot avatar should display the specified image (`bot_avatar.png`) instead of the default text avatar.

**Additional Notes:**
- Ensure the image path is correct and the image file exists in the specified location.
- Test

 the changes on different devices to verify the avatar displays correctly across various screen sizes and resolutions.

---

**Tasks:**
1. **Test Image Rendering:**
- [x] After implementing the image avatar, thoroughly test the chat interface to ensure the image loads correctly. Check for issues such as image not displaying, incorrect sizing, or distortion.

2. **Responsive Design Check:**
- [x] Ensure the avatar image scales appropriately on different devices and screen resolutions. It should not appear pixelated or stretched on larger screens.

3. **Accessibility Considerations:**
- [x] Add alt text or descriptions for the avatar image to support screen readers, enhancing accessibility for visually impaired users.

4. **Performance Optimization:**
- [x] Check the impact of adding the image on app performance, especially on low-end devices. Optimize the image size and format if necessary to ensure smooth performance.

6. **Documentation Update:**
- [x] Update any relevant project documentation to reflect the changes made, including the addition of the avatar image and any new dependencies or assets used.
